<?php
// 
// $Id: ezflowerrenderer.php,v 1.1 2000/10/23 14:33:19 bf-cvs Exp $
//
// Definition of eZFlowerRenderer class
//
// Bård Farstad <bf@ez.no>
// Created on: <23-Oct-2000 15:14:23 bf>
//
// Copyright (C) 1999-2000 eZ Systems.  All rights reserved.
//
// IMPORTANT NOTE: You may NOT copy this file or any part of it into
// your own programs or libraries.
//

//!! eZArticle
//! eZFlowerRenderer renders XML contents into html articles.
/*!
  This class wil decode the flower articles generated by eZFlowerGenerator.

  \sa eZFlowerGenerator  
*/

include_once( "classes/eztexttool.php" );

class eZFlowerRenderer
{
    /*!
      Creates a new eZFlowerGenerator object.
    */
    function eZFlowerRenderer( &$article )
    {
        $this->Article = $article;
    }

    /*!
      Returns the XHTML contents of the introduction of the article.
    */
    function &renderIntro()
    {
        $xml = xmltree( $this->Article->contents() );

        if ( !$xml )
        {
            print( "<br /><b>Error: eZFlowerRenderer::docodeXML() could not decode XML</b><br />" );
        }
        else
        {
            $into = "";
            $body = "";
            
            $i=0;
            foreach ( $xml->root->children as $child )
            {
                if ( $child->name == "intro" )
                {
                    $intro = $child->children[0]->content;
                }

                if ( $child->name == "body" )
                {
                    $body = "<p class=\"pris\">" . $child->children[0]->content . "</p>";
                }
            }

            $newArticle = eZTextTool::nl2br( $intro . $body );
        }
        
        return $newArticle;
    }

    /*!
      Returns the XHTML article of the article.
    */
    function &renderPage( $page=0 )
    {
        $xml = xmltree( $this->Article->contents() );

        if ( !$xml )
        {
            print( "<br /><b>Error: eZFlowerRenderer::docodeXML() could not decode XML</b><br />" );
        }
        else
        {
            $into = "";
            $body = "";
            
            $i=0;
            foreach ( $xml->root->children as $child )
            {
                if ( $child->name == "intro" )
                {
                    $intro = $child->children[0]->content;
                }
                
                if ( $child->name == "body" )
                {
                    $body = $child->children[0]->content;                    
                }
            }

            $newArticle = eZTextTool::nl2br( $intro ) . "</p><p>". eZTextTool::nl2br( $body );
        }
        
        return $newArticle;
    }
    
    var $Article;
}

?>
