

INSERT INTO eZArticle_Article VALUES (3,'Demo article','<?xml version=\"1.0\"?><article><generator>qdom</generator>\n<intro>This is a <bold>demo</bold> article. It will demonstrate the new features in eZ publish 2.2. Templates on tags, nested tags and tables are some of the new renderer features.</intro><body><page><factbox>\r\n<header level=\"3\">This is a factbox</header>\r\nSupported features:\r\n<bullet>\r\nHeaders\r\nStandard formatting\r\nLists\r\nTables\r\nImages\r\nFiles\r\n<bold>Template based tags !</bold></bullet>\r\nGo to <link href=\"developer.ez.no\" text=\"developer.ez.no\" /> for more information.\r\nYou can also have images here.\r\n<image id=\"1\" align=\"center\" size=\"medium\" />\r\n</factbox>\r\n<header level=\"1\">eZ article renderer demo</header>\r\n\r\n<header level=\"2\">Some basic formatting: </header>\r\n<bold>Bold</bold>, <italic>Italic</italic>, <underline>Underline</underline>, <strong>Strong</strong>.\r\n\r\n<header level=\"2\">Images: </header>\r\n\r\n<image id=\"2\" align=\"left\" size=\"medium\" /> You can align images left, right, center or let them float on line with the text.\r\n\r\n\r\n\r\n Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Et harumd und lookum like Greek to me, dereud facilis est er expedit distinct. Nam liber te conscient to factor tum poen legum odioque civiuda. Et tam neque pecun modut est neque nonor et imper ned libidig met, consectetur adipiscing elit, sed ut labore et dolore magna aliquam makes one wonder who would ever read this stuff? Bis nostrud exercitation ullam mmodo consequet. Duis aute in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\r\n\r\n<image id=\"3\" align=\"center\" size=\"medium\" />\r\n\r\n\r\n\r\n Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Et harumd und lookum like Greek to me, dereud facilis est er expedit distinct. Nam liber te conscient to factor tum poen legum odioque civiuda. Et tam neque pecun modut est neque nonor et imper ned libidig met, consectetur adipiscing elit, sed ut labore et dolore magna aliquam makes one wonder who would ever read this stuff? Bis nostrud exercitation ullam mmodo consequet. Duis aute in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\r\n\r\n<table>\r\n<tr>\r\n<td>\r\n<image id=\"4\" align=\"center\" size=\"medium\" /> \r\n</td><td>\r\n<image id=\"5\" align=\"center\" size=\"medium\" /> \r\n</td></tr>\r\n<tr>\r\n<td>\r\n<image id=\"6\" align=\"center\" size=\"medium\" /> \r\n</td><td>\r\nThis is a table example. You can have <bold>tags </bold> in here too.\r\n</td></tr>\r\n</table></page></body></article>',1,'',1,998926647,998925979,998926532,1,1,'qdomThis is a demo article. It will demonstrate the new features in eZ publish 2.2. Templates on tags, nested tags and tables are some of renderer features.This factboxSupported features:HeadersStandard formattingListsTablesImagesFilesTemplate based !Go to  for more information.You can also have images here.eZ article demoSome basic formatting: Bold, Italic, Underline, Strong.Images:  You align left, right, center or let them float line with text. Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo consequat. Duis aute irure reprehenderit voluptate velit esse cillum eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt culpa qui officia deserunt mollit anim id est laborum Et harumd und lookum like Greek me, dereud facilis er expedit distinct. Nam liber te conscient factor tum poen legum odioque civiuda. tam neque pecun modut nonor imper ned libidig met, consectetur adipiscing aliquam makes one wonder who would ever read this stuff? Bis ullam mmodo consequet. pariatur. pariatur.  This table example. here too. ',0,0,0,0,'');

INSERT INTO eZArticle_ArticleCategoryDefinition VALUES (1,3,1);
INSERT INTO eZArticle_ArticleCategoryLink VALUES (3,3,1,3);

INSERT INTO eZArticle_ArticleImageDefinition VALUES (3,2);


INSERT INTO eZArticle_ArticleImageLink VALUES (1,3,1,998926113,1);
INSERT INTO eZArticle_ArticleImageLink VALUES (2,3,2,998926113,2);
INSERT INTO eZArticle_ArticleImageLink VALUES (3,3,3,998926113,3);
INSERT INTO eZArticle_ArticleImageLink VALUES (4,3,4,998926113,4);
INSERT INTO eZArticle_ArticleImageLink VALUES (5,3,5,998926113,5);
INSERT INTO eZArticle_ArticleImageLink VALUES (6,3,6,998926113,6);

INSERT INTO eZArticle_ArticlePermission VALUES (3,3,-1,1,1);

INSERT INTO eZArticle_ArticleWordLink VALUES (1,1);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,2);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,3);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,4);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,5);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,6);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,7);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,8);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,9);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,10);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,11);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,12);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,13);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,14);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,15);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,16);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,17);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,18);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,19);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,20);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,21);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,22);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,23);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,24);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,25);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,26);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,27);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,28);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,29);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,30);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,31);
INSERT INTO eZArticle_ArticleWordLink VALUES (1,3);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,1);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,2);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,3);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,4);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,5);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,6);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,7);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,8);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,9);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,10);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,11);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,12);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,13);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,14);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,15);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,16);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,17);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,18);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,19);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,20);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,21);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,22);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,23);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,24);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,25);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,26);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,27);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,28);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,29);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,30);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,31);
INSERT INTO eZArticle_ArticleWordLink VALUES (2,3);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,3);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,59);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,58);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,57);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,166);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,165);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,164);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,163);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,162);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,161);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,160);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,159);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,158);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,157);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,156);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,155);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,154);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,153);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,152);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,151);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,150);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,149);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,148);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,147);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,146);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,145);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,144);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,143);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,142);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,141);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,140);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,139);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,138);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,137);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,136);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,135);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,134);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,133);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,132);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,131);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,130);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,129);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,128);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,127);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,126);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,125);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,124);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,123);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,122);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,121);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,120);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,119);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,118);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,117);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,116);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,115);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,114);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,113);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,112);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,111);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,110);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,109);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,108);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,107);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,106);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,105);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,104);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,103);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,102);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,101);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,100);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,99);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,98);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,97);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,96);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,95);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,94);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,93);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,92);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,91);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,90);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,89);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,88);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,87);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,86);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,85);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,84);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,83);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,82);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,81);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,80);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,79);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,78);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,77);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,76);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,75);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,74);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,73);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,72);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,71);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,70);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,69);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,68);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,67);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,66);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,65);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,64);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,63);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,62);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,61);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,60);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,55);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,54);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,53);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,52);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,51);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,50);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,49);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,48);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,47);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,46);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,45);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,38);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,37);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,36);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,35);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,34);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,33);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,32);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,44);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,39);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,43);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,42);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,41);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,40);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,31);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,30);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,29);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,28);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,169);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,168);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,167);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,26);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,25);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,24);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,23);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,22);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,21);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,20);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,19);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,18);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,17);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,16);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,15);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,14);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,13);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,12);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,11);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,10);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,9);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,8);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,7);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,6);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,5);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,4);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,3);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,2);
INSERT INTO eZArticle_ArticleWordLink VALUES (3,1);

INSERT INTO eZArticle_Category VALUES (1,'Put articles here','A category to store articles.',0,0,1,1,1,1,2,0);

INSERT INTO eZArticle_CategoryPermission VALUES (1,1,-1,1,1);


INSERT INTO eZArticle_Word VALUES (1,'qdomthis');
INSERT INTO eZArticle_Word VALUES (2,'is');
INSERT INTO eZArticle_Word VALUES (3,'demo');
INSERT INTO eZArticle_Word VALUES (4,'article');
INSERT INTO eZArticle_Word VALUES (5,'it');
INSERT INTO eZArticle_Word VALUES (6,'will');
INSERT INTO eZArticle_Word VALUES (7,'demonstrate');
INSERT INTO eZArticle_Word VALUES (8,'the');
INSERT INTO eZArticle_Word VALUES (9,'new');
INSERT INTO eZArticle_Word VALUES (10,'features');
INSERT INTO eZArticle_Word VALUES (11,'in');
INSERT INTO eZArticle_Word VALUES (12,'ez');
INSERT INTO eZArticle_Word VALUES (13,'publish');
INSERT INTO eZArticle_Word VALUES (14,'templates');
INSERT INTO eZArticle_Word VALUES (15,'on');
INSERT INTO eZArticle_Word VALUES (16,'tags');
INSERT INTO eZArticle_Word VALUES (17,'nested');
INSERT INTO eZArticle_Word VALUES (18,'and');
INSERT INTO eZArticle_Word VALUES (19,'tables');
INSERT INTO eZArticle_Word VALUES (20,'are');
INSERT INTO eZArticle_Word VALUES (21,'some');
INSERT INTO eZArticle_Word VALUES (22,'of');
INSERT INTO eZArticle_Word VALUES (23,'renderer');
INSERT INTO eZArticle_Word VALUES (24,'this');
INSERT INTO eZArticle_Word VALUES (25,'factboxsupported');
INSERT INTO eZArticle_Word VALUES (26,'headersstandard');
INSERT INTO eZArticle_Word VALUES (27,'formattingliststablesimagesfilesgo');
INSERT INTO eZArticle_Word VALUES (28,'to');
INSERT INTO eZArticle_Word VALUES (29,'for');
INSERT INTO eZArticle_Word VALUES (30,'more');
INSERT INTO eZArticle_Word VALUES (31,'information');
INSERT INTO eZArticle_Word VALUES (32,'demosome');
INSERT INTO eZArticle_Word VALUES (33,'basic');
INSERT INTO eZArticle_Word VALUES (34,'formatting');
INSERT INTO eZArticle_Word VALUES (35,'bold');
INSERT INTO eZArticle_Word VALUES (36,'italic');
INSERT INTO eZArticle_Word VALUES (37,'underline');
INSERT INTO eZArticle_Word VALUES (38,'strong');
INSERT INTO eZArticle_Word VALUES (39,'images');
INSERT INTO eZArticle_Word VALUES (40,'you');
INSERT INTO eZArticle_Word VALUES (41,'can');
INSERT INTO eZArticle_Word VALUES (42,'also');
INSERT INTO eZArticle_Word VALUES (43,'have');
INSERT INTO eZArticle_Word VALUES (44,'here');
INSERT INTO eZArticle_Word VALUES (45,'align');
INSERT INTO eZArticle_Word VALUES (46,'left');
INSERT INTO eZArticle_Word VALUES (47,'right');
INSERT INTO eZArticle_Word VALUES (48,'center');
INSERT INTO eZArticle_Word VALUES (49,'or');
INSERT INTO eZArticle_Word VALUES (50,'let');
INSERT INTO eZArticle_Word VALUES (51,'them');
INSERT INTO eZArticle_Word VALUES (52,'float');
INSERT INTO eZArticle_Word VALUES (53,'line');
INSERT INTO eZArticle_Word VALUES (54,'with');
INSERT INTO eZArticle_Word VALUES (55,'text');
INSERT INTO eZArticle_Word VALUES (56,'imagefloating');
INSERT INTO eZArticle_Word VALUES (57,'table');
INSERT INTO eZArticle_Word VALUES (58,'example');
INSERT INTO eZArticle_Word VALUES (59,'too');
INSERT INTO eZArticle_Word VALUES (60,'lorem');
INSERT INTO eZArticle_Word VALUES (61,'ipsum');
INSERT INTO eZArticle_Word VALUES (62,'dolor');
INSERT INTO eZArticle_Word VALUES (63,'sit');
INSERT INTO eZArticle_Word VALUES (64,'amet');
INSERT INTO eZArticle_Word VALUES (65,'consectetaur');
INSERT INTO eZArticle_Word VALUES (66,'adipisicing');
INSERT INTO eZArticle_Word VALUES (67,'elit');
INSERT INTO eZArticle_Word VALUES (68,'sed');
INSERT INTO eZArticle_Word VALUES (69,'do');
INSERT INTO eZArticle_Word VALUES (70,'eiusmod');
INSERT INTO eZArticle_Word VALUES (71,'tempor');
INSERT INTO eZArticle_Word VALUES (72,'incididunt');
INSERT INTO eZArticle_Word VALUES (73,'ut');
INSERT INTO eZArticle_Word VALUES (74,'labore');
INSERT INTO eZArticle_Word VALUES (75,'et');
INSERT INTO eZArticle_Word VALUES (76,'dolore');
INSERT INTO eZArticle_Word VALUES (77,'magna');
INSERT INTO eZArticle_Word VALUES (78,'aliqua');
INSERT INTO eZArticle_Word VALUES (79,'enim');
INSERT INTO eZArticle_Word VALUES (80,'ad');
INSERT INTO eZArticle_Word VALUES (81,'minim');
INSERT INTO eZArticle_Word VALUES (82,'veniam');
INSERT INTO eZArticle_Word VALUES (83,'quis');
INSERT INTO eZArticle_Word VALUES (84,'nostrud');
INSERT INTO eZArticle_Word VALUES (85,'exercitation');
INSERT INTO eZArticle_Word VALUES (86,'ullamco');
INSERT INTO eZArticle_Word VALUES (87,'laboris');
INSERT INTO eZArticle_Word VALUES (88,'nisi');
INSERT INTO eZArticle_Word VALUES (89,'aliquip');
INSERT INTO eZArticle_Word VALUES (90,'ex');
INSERT INTO eZArticle_Word VALUES (91,'ea');
INSERT INTO eZArticle_Word VALUES (92,'commodo');
INSERT INTO eZArticle_Word VALUES (93,'consequat');
INSERT INTO eZArticle_Word VALUES (94,'duis');
INSERT INTO eZArticle_Word VALUES (95,'aute');
INSERT INTO eZArticle_Word VALUES (96,'irure');
INSERT INTO eZArticle_Word VALUES (97,'reprehenderit');
INSERT INTO eZArticle_Word VALUES (98,'voluptate');
INSERT INTO eZArticle_Word VALUES (99,'velit');
INSERT INTO eZArticle_Word VALUES (100,'esse');
INSERT INTO eZArticle_Word VALUES (101,'cillum');
INSERT INTO eZArticle_Word VALUES (102,'eu');
INSERT INTO eZArticle_Word VALUES (103,'fugiat');
INSERT INTO eZArticle_Word VALUES (104,'nulla');
INSERT INTO eZArticle_Word VALUES (105,'pariatur');
INSERT INTO eZArticle_Word VALUES (106,'excepteur');
INSERT INTO eZArticle_Word VALUES (107,'sint');
INSERT INTO eZArticle_Word VALUES (108,'occaecat');
INSERT INTO eZArticle_Word VALUES (109,'cupidatat');
INSERT INTO eZArticle_Word VALUES (110,'non');
INSERT INTO eZArticle_Word VALUES (111,'proident');
INSERT INTO eZArticle_Word VALUES (112,'sunt');
INSERT INTO eZArticle_Word VALUES (113,'culpa');
INSERT INTO eZArticle_Word VALUES (114,'qui');
INSERT INTO eZArticle_Word VALUES (115,'officia');
INSERT INTO eZArticle_Word VALUES (116,'deserunt');
INSERT INTO eZArticle_Word VALUES (117,'mollit');
INSERT INTO eZArticle_Word VALUES (118,'anim');
INSERT INTO eZArticle_Word VALUES (119,'id');
INSERT INTO eZArticle_Word VALUES (120,'est');
INSERT INTO eZArticle_Word VALUES (121,'laborum');
INSERT INTO eZArticle_Word VALUES (122,'harumd');
INSERT INTO eZArticle_Word VALUES (123,'und');
INSERT INTO eZArticle_Word VALUES (124,'lookum');
INSERT INTO eZArticle_Word VALUES (125,'like');
INSERT INTO eZArticle_Word VALUES (126,'greek');
INSERT INTO eZArticle_Word VALUES (127,'me');
INSERT INTO eZArticle_Word VALUES (128,'dereud');
INSERT INTO eZArticle_Word VALUES (129,'facilis');
INSERT INTO eZArticle_Word VALUES (130,'er');
INSERT INTO eZArticle_Word VALUES (131,'expedit');
INSERT INTO eZArticle_Word VALUES (132,'distinct');
INSERT INTO eZArticle_Word VALUES (133,'nam');
INSERT INTO eZArticle_Word VALUES (134,'liber');
INSERT INTO eZArticle_Word VALUES (135,'te');
INSERT INTO eZArticle_Word VALUES (136,'conscient');
INSERT INTO eZArticle_Word VALUES (137,'factor');
INSERT INTO eZArticle_Word VALUES (138,'tum');
INSERT INTO eZArticle_Word VALUES (139,'poen');
INSERT INTO eZArticle_Word VALUES (140,'legum');
INSERT INTO eZArticle_Word VALUES (141,'odioque');
INSERT INTO eZArticle_Word VALUES (142,'civiuda');
INSERT INTO eZArticle_Word VALUES (143,'tam');
INSERT INTO eZArticle_Word VALUES (144,'neque');
INSERT INTO eZArticle_Word VALUES (145,'pecun');
INSERT INTO eZArticle_Word VALUES (146,'modut');
INSERT INTO eZArticle_Word VALUES (147,'nonor');
INSERT INTO eZArticle_Word VALUES (148,'imper');
INSERT INTO eZArticle_Word VALUES (149,'ned');
INSERT INTO eZArticle_Word VALUES (150,'libidig');
INSERT INTO eZArticle_Word VALUES (151,'met');
INSERT INTO eZArticle_Word VALUES (152,'consectetur');
INSERT INTO eZArticle_Word VALUES (153,'adipiscing');
INSERT INTO eZArticle_Word VALUES (154,'aliquam');
INSERT INTO eZArticle_Word VALUES (155,'makes');
INSERT INTO eZArticle_Word VALUES (156,'one');
INSERT INTO eZArticle_Word VALUES (157,'wonder');
INSERT INTO eZArticle_Word VALUES (158,'who');
INSERT INTO eZArticle_Word VALUES (159,'would');
INSERT INTO eZArticle_Word VALUES (160,'ever');
INSERT INTO eZArticle_Word VALUES (161,'read');
INSERT INTO eZArticle_Word VALUES (162,'stuff');
INSERT INTO eZArticle_Word VALUES (163,'bis');
INSERT INTO eZArticle_Word VALUES (164,'ullam');
INSERT INTO eZArticle_Word VALUES (165,'mmodo');
INSERT INTO eZArticle_Word VALUES (166,'consequet');
INSERT INTO eZArticle_Word VALUES (167,'formattingliststablesimagesfilestemplate');
INSERT INTO eZArticle_Word VALUES (168,'based');
INSERT INTO eZArticle_Word VALUES (169,'go');

INSERT INTO eZImageCatalogue_Category VALUES (1,'Shared images','Images you can use in articles for demo.',0,1,1,1);

INSERT INTO eZImageCatalogue_CategoryPermission VALUES (1,1,-1,1,1);

INSERT INTO eZImageCatalogue_Image VALUES (1,'The river','The river','River',1,998925431,'phpV0ASdp.jpg','dscn0594.jpg',0,0,1,'');
INSERT INTO eZImageCatalogue_Image VALUES (2,'Blue flower','Blue flower','Blue flower',1,998925461,'phpIUQCV0.jpg','dscn1771.jpg',0,0,1,'');
INSERT INTO eZImageCatalogue_Image VALUES (3,'Clover','Clover','Clover',1,998925544,'phpH8gAOd.jpg','dscn3022.jpg',0,0,1,'');
INSERT INTO eZImageCatalogue_Image VALUES (4,'Pond','Pond','Pond',1,998925592,'phpaGGaI6.jpg','dscn3037.jpg',0,0,1,'');
INSERT INTO eZImageCatalogue_Image VALUES (5,'Branch','Branch','Branch',1,998925628,'phpdTR1fj.jpg','dscn3122.jpg',0,0,1,'');
INSERT INTO eZImageCatalogue_Image VALUES (6,'Yellow flower','Yellow flower','Yellow flower',1,998925646,'phpRAxqEK.jpg','dscn3251.jpg',0,0,1,'');

INSERT INTO eZImageCatalogue_ImageCategoryDefinition VALUES (1,1,1);
INSERT INTO eZImageCatalogue_ImageCategoryDefinition VALUES (2,2,1);
INSERT INTO eZImageCatalogue_ImageCategoryDefinition VALUES (3,3,1);
INSERT INTO eZImageCatalogue_ImageCategoryDefinition VALUES (4,4,1);
INSERT INTO eZImageCatalogue_ImageCategoryDefinition VALUES (5,5,1);
INSERT INTO eZImageCatalogue_ImageCategoryDefinition VALUES (6,6,1);

INSERT INTO eZImageCatalogue_ImageCategoryLink VALUES (1,1,1);
INSERT INTO eZImageCatalogue_ImageCategoryLink VALUES (2,1,2);
INSERT INTO eZImageCatalogue_ImageCategoryLink VALUES (3,1,3);
INSERT INTO eZImageCatalogue_ImageCategoryLink VALUES (4,1,4);
INSERT INTO eZImageCatalogue_ImageCategoryLink VALUES (5,1,5);
INSERT INTO eZImageCatalogue_ImageCategoryLink VALUES (6,1,6);

INSERT INTO eZImageCatalogue_ImagePermission VALUES (1,1,-1,1,1);
INSERT INTO eZImageCatalogue_ImagePermission VALUES (2,2,-1,1,1);
INSERT INTO eZImageCatalogue_ImagePermission VALUES (3,3,-1,1,1);
INSERT INTO eZImageCatalogue_ImagePermission VALUES (4,4,-1,1,1);
INSERT INTO eZImageCatalogue_ImagePermission VALUES (5,5,-1,1,1);
INSERT INTO eZImageCatalogue_ImagePermission VALUES (6,6,-1,1,1);

INSERT INTO eZImageCatalogue_ImageVariation VALUES (1,1,1,'ezimagecatalogue/catalogue/variations/1-150x150.jpg',150,112,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (2,2,1,'ezimagecatalogue/catalogue/variations/2-150x150.jpg',150,112,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (3,3,1,'ezimagecatalogue/catalogue/variations/3-150x150.jpg',150,112,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (4,4,1,'ezimagecatalogue/catalogue/variations/4-150x150.jpg',150,112,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (5,5,1,'ezimagecatalogue/catalogue/variations/5-150x150.jpg',150,112,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (6,6,1,'ezimagecatalogue/catalogue/variations/6-150x150.jpg',150,112,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (7,6,2,'ezimagecatalogue/catalogue/variations/6-400x500.jpg',266,200,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (8,2,2,'ezimagecatalogue/catalogue/variations/2-400x500.jpg',266,200,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (9,1,3,'ezimagecatalogue/catalogue/variations/1-100x100.jpg',100,75,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (10,1,4,'ezimagecatalogue/catalogue/variations/1-200x200.jpg',200,150,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (11,2,4,'ezimagecatalogue/catalogue/variations/2-200x200.jpg',200,150,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (12,3,4,'ezimagecatalogue/catalogue/variations/3-200x200.jpg',200,150,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (13,4,3,'ezimagecatalogue/catalogue/variations/4-100x100.jpg',100,75,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (14,5,3,'ezimagecatalogue/catalogue/variations/5-100x100.jpg',100,75,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (15,6,3,'ezimagecatalogue/catalogue/variations/6-100x100.jpg',100,75,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (16,4,4,'ezimagecatalogue/catalogue/variations/4-200x200.jpg',200,150,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (17,5,4,'ezimagecatalogue/catalogue/variations/5-200x200.jpg',200,150,'');
INSERT INTO eZImageCatalogue_ImageVariation VALUES (18,6,4,'ezimagecatalogue/catalogue/variations/6-200x200.jpg',200,150,'');

INSERT INTO eZImageCatalogue_ImageVariationGroup VALUES (1,150,150);
INSERT INTO eZImageCatalogue_ImageVariationGroup VALUES (2,400,500);
INSERT INTO eZImageCatalogue_ImageVariationGroup VALUES (3,100,100);
INSERT INTO eZImageCatalogue_ImageVariationGroup VALUES (4,200,200);

INSERT INTO eZUser_Author VALUES (1,'Admin Author','nospam@nospam.com');


INSERT INTO eZPoll_MainPoll VALUES (1,1);

INSERT INTO eZPoll_Poll VALUES (1,'Coolest new feature in 2.2 is','No description for this poll.',1,1,0,1);

INSERT INTO eZPoll_PollChoice VALUES (1,1,'Article templates',0);
INSERT INTO eZPoll_PollChoice VALUES (2,1,'Postgresql support',0);
INSERT INTO eZPoll_PollChoice VALUES (3,1,'Nested article tags',0);
INSERT INTO eZPoll_PollChoice VALUES (4,1,'Extended link database',0);

INSERT INTO eZPoll_Vote VALUES (1,1,1,'10.0.2.3',0);


INSERT INTO eZForum_Category VALUES ('Discussion','',0,1);
INSERT INTO eZForum_Forum VALUES ('Public forum','Public forum',0,2,0,0,0,1);

INSERT INTO eZForum_Message VALUES (2,'First post!','Yes ! I was the first to post here..\r\n\r\n--foo',0,0,0,998928123,0,0,0,1,1,0);


INSERT INTO eZLink_Attribute VALUES (1,1,'Price',998928426,0,'');
INSERT INTO eZLink_Attribute VALUES (2,1,'License',998928428,1,'');
INSERT INTO eZLink_Attribute VALUES (3,1,'Features',998928448,2,'');

INSERT INTO eZLink_AttributeValue VALUES (3,1,3,'Numerous..');
INSERT INTO eZLink_AttributeValue VALUES (2,1,2,'GPL');
INSERT INTO eZLink_AttributeValue VALUES (1,1,1,'$ 0');

INSERT INTO eZLink_Category VALUES (1,0,'Links',2,'Links');

INSERT INTO eZLink_Link VALUES (1,'eZ publish','GPL web application software.',NULL,'ez publish',998928575,1,998928399,'developer.ez.no',2);

INSERT INTO eZLink_LinkCategoryDefinition VALUES (1,1,1);

INSERT INTO eZLink_LinkCategoryLink VALUES (1,1,1);

INSERT INTO eZLink_Type VALUES (1,'Software vendor');

INSERT INTO eZLink_TypeLink VALUES (1,1,1);
INSERT INTO eZTrade_Category VALUES (1,0,' ','Producs for sale',1,1,'');
INSERT INTO eZTrade_CategoryPermission VALUES (1,1,-1,1,1);
INSERT INTO eZTrade_Product VALUES (1,'Piranha pond','\n<?xml version=\"1.0\"?><article><generator>qdom</generator><intro>\nLorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut \nlabore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui \nofficia deserunt mollit anim id est laborum Et harumd und lookum like Greek to me, dereud facilis est er expedit distinct. Nam liber te conscient to factor tum poen legum odioque civiuda. \nEt tam neque pecun modut est neque nonor et imper ned libidig met, consectetur adipiscing elit, sed ut labore et dolore magna aliquam makes one wonder who would ever read this stuff? \nBis nostrud exercitation ullam mmodo consequet. Duis aute in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n</intro><body><page>\nLorem ipsum dolor sit amet, consectetaur adipisicing elit, \nsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco \nlaboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \nExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Et harumd und lookum like Greek to me, \ndereud facilis est er expedit distinct. Nam liber te conscient to factor tum poen legum odioque civiuda. Et tam neque pecun modut est neque nonor et imper ned libidig\n elit, sed ut labore et dolore magna aliquam makes one wonder who would ever read this stuff? Bis nostrud exercitation ullam mmodo consequet. Duis aute in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n</page></body></article>','','','',1001.00000,1,1,0,'P-1001','developer.ez.no',1,'',1,1,0,0,998929107);

INSERT INTO eZTrade_ProductCategoryDefinition VALUES (1,1,1);

INSERT INTO eZTrade_ProductCategoryLink VALUES (1,1,1,1);
INSERT INTO eZTrade_ProductImageDefinition VALUES (1,4,4);

INSERT INTO eZTrade_ProductImageLink VALUES (1,0,1,1,0);
INSERT INTO eZTrade_ProductImageLink VALUES (2,0,1,3,0);
INSERT INTO eZTrade_ProductImageLink VALUES (3,0,1,4,0);
INSERT INTO eZTrade_ProductPermission VALUES (1,1,-1,0,0);

INSERT INTO eZTrade_ProductQuantityDict VALUES (1,1);

INSERT INTO eZTrade_Quantity VALUES (1,100);

INSERT INTO eZTrade_ShippingGroup VALUES (1,'Standard shipping',998929027);

INSERT INTO eZTrade_ShippingType VALUES (1,'DHL',998929024,1,1);

INSERT INTO eZTrade_ShippingValue VALUES (1,1,1,10,3);

INSERT INTO eZTrade_VATType VALUES (1,'Standard VAT',24,998928974);
INSERT INTO eZTrade_VATType VALUES (2,'No VAT',0,998929000);
